// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
struct GrassData
{
    float3 position;
};

RWStructuredBuffer<GrassData> grassBuffer;

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;

    GrassData g;
    g.position = float3(index,0,0);
    grassBuffer[index] = g;

}
